name: 2
on:
  pull_request:
jobs:
  node_setup:
    runs-on: ubuntu-latest
    env:
      DEFAULT_NODE_VERSION: '12.16.1'
      USE_NVMRC: 'false'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment with env
        if: env.USE_NVMRC == 'false'
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - name: Read node version from .nvmrc
        if: env.USE_NVMRC == 'true'
        run: echo ::set-output name=NVMRC_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Setup Node.js environment with version from .nvmrc
        if: env.USE_NVMRC == 'true'
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC_VERSION }}
      - name: Install packages
        run: npm install