name: 'Terraform Apply'

# Always start workflow even if there are no changes to the terraform configurations for the environmnet
# so other workflows can depend on this workflow completing before starting (Continuous Deployment).
on:
  push:
    branches:
      - develop

jobs:
  # Check if there are any changes to the terraform directory. We only want to run the following
  # jobs if the configurations have changed. So if there were no changes then the workflow will
  # complete after this job ends.
  changes:
    name: 'Check Changes'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v3
      with:
        filters: |
          src:
            - 'iac/**'

  # Set Environment will only run if the Check Changes job detected changes in the terraform configs.
  set_environment:
    name: "Set Environment"
    needs: changes
    if: ${{ needs.changes.outputs.src == 'src' }}
    runs-on: ubuntu-latest
    outputs:
      my_env: ${{ steps.setenv.outputs.my_env }}
    steps:
      - id: setenv
        run: |
          if [ "${{github.ref_name}}" == "develop" ]; then 
            echo "my_env=Develop" >> "$GITHUB_OUTPUT";
          fi
  terraform_apply:
    name: 'Terraform Apply'
    needs: set_environment
    runs-on: ubuntu-latest
    steps:
      - run: echo 'apply terraform'